apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
commonLabels:
  app: gsv
  env: dev
commonAnnotations:
  app: gsv
  env: dev

resources:
  - ../../base/

patchesStrategicMerge:
  - patch-deploy.yaml
  - patch-hpa.yaml
  - patch-cm.yaml
