apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jackpotland

resources:
- ../../base

patchesStrategicMerge:
- patch-config.yaml
- patch-deployment.yaml
- patch-deployment-health.yaml
- patch-deployment-memory.yaml
- patch-hpa.yaml
nameSuffix: -dev-1.0.0
commonLabels:
  app: gsv-dev-1.0.0
images:
- name: harbor.nuclearport.com/jackpotland/gsv
  newTag: 1.0.0
configMapGenerator:
- literals:
  - env=dev
  - vsn=1.0.0
  name: gsv-config-dev-1.0.0
