apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jackpotland
resources:
    - ../../base


nameSuffix: -dev-v
commonLabels:
    app: gsv
    env: pre

patchesStrategicMerge:
    - patch-config.yaml
    - patch-deployment.yaml
    - patch-deployment-health.yaml
    - patch-deployment-memory.yaml
    - patch-hpa.yaml

