apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -pre
commonLabels:
  app: gsv
  env: pre
commonAnnotations:
  app: gsv
  env: pre

resources:
  - ../../base/

patchesStrategicMerge:
  - patch-deploy.yaml
  - patch-hpa.yaml
  - patch-cm.yaml
