apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jackpotland

resources:
    - ../../base

patchesStrategicMerge:
    - patch-config.yaml
    - patch-deployment.yaml
    - patch-deployment-health.yaml
    - patch-deployment-memory.yaml
    - patch-hpa.yaml
    -
nameSuffix: -pro-e
commonLabels:
    app: gsv
    env: pre
#
#configMapGenerator:
#    -   literals:
#            - vsn=1.0.0
#            - env=pro
#        name: gsv-config
