kind: Deployment
apiVersion: apps/v1
metadata:
  name: gsv-deployment
spec:
  template:
    spec:
      containers:
        - name: gsv-pod
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 25Mi

