apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: gsv====
    name: '---jackpotlandgsv-deploymentjackpotland---'
    namespace: jackpotland===
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gsv====
    strategy:
        rollingUpdate:
            maxSurge: 50%
            maxUnavailable: 50%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: gsv====
        spec:
            affinity:
                podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                        - podAffinityTerm:
                              labelSelector:
                                  matchLabels:
                                      app: gsv====
                              topologyKey: kubernetes.io/hostname
                          weight: 100
            containers:
                - env:
                      - name: env
                        valueFrom:
                            configMapKeyRef:
                                key: env
                                name: '---jackpotlandgsv-configjackpotland---'
                      - name: vsn
                        valueFrom:
                            configMapKeyRef:
                                key: vsn
                                name: '---jackpotlandgsv-configjackpotland---'
                  image: harbor.nuclearport.com/jackpotland/game_slots_vsn:1.0.0
                  imagePullPolicy: Always
                  livenessProbe:
                      failureThreshold: 3
                      httpGet:
                          path: /heartbeat
                          port: 9091
                          scheme: HTTP
                      initialDelaySeconds: 10
                      periodSeconds: 10
                      successThreshold: 1
                      timeoutSeconds: 1
                  name: gsv-pod
                  ports:
                      - containerPort: 9091
                        name: http-9091
                        protocol: TCP
                  startupProbe:
                      failureThreshold: 3
                      httpGet:
                          path: /heartbeat
                          port: 9091
                          scheme: HTTP
                      initialDelaySeconds: 10
                      periodSeconds: 10
                      successThreshold: 1
                      timeoutSeconds: 1
            imagePullSecrets:
                - name: jackpotland-image-repository-secret