apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jackpotland===
nameSuffix: jackpotland---
namePrefix: ---jackpotland
commonLabels:
    app: gsv====
resources:
    - service.yaml
    - deployment.yaml
    - config.yaml
    - hpa.yaml
