apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - config.yaml
    - deployment.yaml
    - hpa.yaml
    - service.yaml

#namespace: jackpotland

##kustomize edit set namesuffix -dev-v1.0.0
#nameSuffix: -dev-v1.0.0

##kustomize edit set label app:gsv env:dev vsn:1.0.0
#commonLabels:
#    app: gsv
#    env: dev
#    vsn: 1.0.0

##kustomize edit set image harbor.nuclearport.com/jackpotland/game_slots_vsn:1.0.0
#images:
#    -   name: harbor.nuclearport.com/jackpotland/game_slots_vsn
#        newTag: 1.0.0

#kustomize edit add configmap gsv-config --from-literal=vsn=1.0.0 --from-literal=env=dev
#configMapGenerator:
#    -   literals:
#            - vsn=1.0.0
#            - env=dev
#        name: gsv-config-pro-v1.0.0