apiVersion: v1
kind: Service
metadata:
    name: aman-svc
spec:
    ports:
        -   port: 50600
            protocol: TCP
            targetPort: 50600
    selector:
        app: aman
    type: NodePort