apiVersion: v1
kind: Service
metadata:
    labels:
        app: gsv====
    name: '---jackpotlandgsv-servicejackpotland---'
    namespace: jackpotland===
spec:
    ports:
        - name: http-19091
          nodePort: 30375
          port: 19091
          protocol: TCP
          targetPort: 9091
    selector:
        app: gsv====
    type: NodePort