# 开发环境
app:
    runMode: "debug"

server:
    ip: "127.0.0.1"
    port: 9091

redis:
    #    masterName: "redis"
    password: ""
    hosts:
        - "10.240.10.153:6379"
    db: 15
    poolSize: 10

log:
    fileEnable: true
    fileName: "./logs/gs_vsn.log"
    fileLevel: info

    consoleEnable: true
    consoleLevel: debug

    maxSize: 20
    maxBackups: 10
    maxAges: 30
    compress: true
    jsonEnable: true

ggeoip:
    name: "ggeoip.mmdb"
    path: "./data/"
    url: "https://geoip.ftsview.com/GeoLite2-City.mmdb"
    duration: 1 #hour


