kind: Service
apiVersion: v1
metadata:
    namespace: jackpotland
    name: gs-service
    labels:
        app: gs-service
spec:
    ports:
        -   name: http-19091
            protocol: TCP
            port: 19091
            targetPort: 9091
            nodePort: 30375
    selector:
        app: gsv-deploy
    type: NodePort
