commonLabels:
    app: game-slots-vsn
namePrefix: pro-
resources:
    - ../../base2
patchesStrategicMerge:
    - patch-deployment.yaml
    - patch-healthcheck.yaml
    - patch-memorylimit.yaml
    - remove-hpa.yaml
