apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -pro
commonLabels:
  app: gsv
  env: pro
commonAnnotations:
  app: gsv
  env: pro

resources:
  - ../../base/

patchesStrategicMerge:
  - patch-deploy.yaml
  - patch-hpa.yaml
  - patch-cm.yaml