apiVersion: apps/v1
kind: Deployment
metadata:
  name: aman
spec:
  template:
    spec:
      containers:
        - name: aman
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /heartbeat
              port: 50600
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /heartbeat
              port: 50600
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1