commonLabels:
    app: aman
namePrefix: prod-
resources:
    - ../../base2
patchesStrategicMerge:
    - deployment-patch.yaml
    - healthcheck_patch.yaml
    - memorylimit_patch.yaml
    - remove-hpa.yaml
